# Generated by Django 5.0 on 2025-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
