# Generated by Django 5.0 on 2025-09-13 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_review_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="liked_users",
            field=models.ManyToManyField(
                blank=True, related_name="liked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="popularity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
