# Generated by Django 5.0 on 2025-09-14 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_review_liked_users_review_popularity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
