# Generated by Django 5.0 on 2025-09-15 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="day",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
