# Generated by Django 5.0 on 2025-09-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_requestedmovie"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedmovie",
            name="description",
            field=models.TextField(default="not"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requestedmovie",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
